version: '3.7'
services:
  frontend:
    build: ./frontend
    container_name: frontend-con
    user: "node"
    working_dir: /metis/frontend
    depends_on:
      - "backend"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/metis/frontend
    networks:
      metis_net:

  backend:
    container_name: backend-con
    restart: unless-stopped
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    depends_on:
      - "postgres"
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/metis/backend
    networks:
      metis_net:

  postgres:
    image: postgres:11
    container_name: postgres-con
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      DATABASE_URL: postgresql://localhost:5432/db
    expose:
      - "5432"
    networks:
      metis_net:
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  metis_net:

volumes:
  db_data:
